name: Checkly API tests

on:
  push:
    branches: [ main ]

jobs:
  run-checkly-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Run Checkly tests
        run: npm test

      - name: Deploy to release branch
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t my-registry/my-node-app:latest -f dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          git checkout -b release
          docker push my-registry/my-node-app:latest
          git add .
          git commit -m "Deploy to release branch"
          git push --set-upstream origin release
